# Starter pipeline for Azure DevOps
# Minimal build + test pipeline

trigger:
- main   # Run pipeline on changes to main branch

pool:
  vmImage: ubuntu-latest

steps:
- task: UseNode@1
  inputs:
    version: '18.x'
  displayName: 'Set up Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build project'

- script: npm test
  displayName: 'Run tests'
